// Starter articles for the Learn / Blog tab.
// These show up until the trainer saves any change to the blog, after which the list lives in Firestore (key: app:blogPosts).

export const BLOG_CATEGORIES = ["Training", "Nutrition", "Fat Loss", "Recovery", "Mindset"];

export const DEFAULT_BLOG_POSTS = [
  {
    "id": "starter-1",
    "title": "Can You Lose Belly Fat? What Actually Works",
    "category": "Fat Loss",
    "excerpt": "It's the most common question I get. Here's the truth about where fat comes off and what to do instead.",
    "date": "2026-09-19",
    "body": "Almost every new client asks me the same thing: \"How do I get rid of my belly?\" Here's the honest answer.\n\n**You can't spot-reduce fat.** Crunches, sit-ups, and waist twisters strengthen the muscles under the fat, but they don't pull fat off that specific area. Your body decides where fat comes off, based on genetics, hormones, and age. The belly is often the last place to shrink and the first place to grow.\n\n**What does work:**\n\n1. **A modest calorie deficit.** Fat loss only happens when you consistently take in a little less energy than you burn. Small and steady beats extreme. A deficit of about 300 to 500 calories a day is a good starting point for most people.\n2. **Strength training 2 to 4 days a week.** Lifting protects your muscle while you lose fat, so you end up leaner instead of just smaller.\n3. **Enough protein.** It keeps you fuller and helps preserve muscle. (See our protein guide in the blog.)\n4. **Daily walking.** Aim for 7,000 to 10,000 steps. It burns extra calories without wearing you out, so it's easier to stay consistent.\n5. **Sleep and stress.** Short sleep makes hunger and cravings harder to control. Aim for 7 to 9 hours.\n6. **Watch liquid calories.** Alcohol, sweet coffee drinks, and sodas add up fast and rarely fill you up.\n\n**Be patient.** Belly fat usually goes down as your overall body fat goes down. Track your weight trend, your waist measurement, and how your clothes fit, not just the scale on one day.\n\n**The takeaway:** Skip the ab-only routines and the \"belly fat\" teas. Build a simple plan around your food, lifting, walking, and sleep, and stick with it.\n\n*Educational content only, not medical advice. Talk to your doctor before starting a new diet or exercise program.*"
  },
  {
    "id": "starter-2",
    "title": "How Much Protein Do You Really Need?",
    "category": "Nutrition",
    "excerpt": "Protein helps you build muscle, lose fat, and stay full. Here's how much to eat and how to hit your number.",
    "date": "2026-09-19",
    "body": "Protein is one of the most talked-about nutrients in fitness, and for good reason. It helps you build and keep muscle, recover from workouts, and feel full between meals.\n\n**How much do you need?**\n\nThe official minimum to avoid deficiency is low, about 0.36 grams per pound of body weight. That's not what most active people should aim for. For people who train and want to build muscle or lose fat, research supports roughly:\n\n**0.7 to 1 gram of protein per pound of body weight per day.**\n\nExample: a 180 lb person would aim for about 125 to 180 grams a day. If you have a lot of body fat to lose, you can base the number on your goal weight instead.\n\n**How to hit it:**\n\n- Spread it across 3 to 5 meals, around 25 to 40 grams each.\n- Build each meal around a protein: chicken, turkey, lean beef, fish, eggs, Greek yogurt, cottage cheese, tofu, or beans and lentils.\n- Use a protein shake as a convenience tool, not a requirement.\n- Track your intake for a week or two. Most people are surprised by how low they actually are.\n\n**Common questions**\n\n*Is more always better?* No. Past about 1 gram per pound, extra protein doesn't add much benefit for most people.\n\n*Is high protein bad for your kidneys?* In healthy people, no evidence shows harm. If you have kidney disease or any medical condition, ask your doctor what's right for you.\n\n*Do I need protein right after my workout?* Not urgently. Your total for the day matters much more than exact timing.\n\n**The takeaway:** Pick a daily target, build your meals around protein, and stay consistent.\n\n*Educational content only, not medical advice. Talk to your doctor before making major changes to your diet.*"
  },
  {
    "id": "starter-3",
    "title": "How to Build Muscle: A Beginner's Guide",
    "category": "Training",
    "excerpt": "Building muscle comes down to a few simple principles. Here's what to focus on and what to ignore.",
    "date": "2026-09-19",
    "body": "Building muscle isn't complicated, but it does need to be done consistently. These are the basics that matter most.\n\n**1. Progressive overload**\n\nYour muscles grow when you ask them to do more than they're used to. That can mean adding weight, doing more reps, adding a set, or improving your form and control. Log your workouts so you know what to beat next time.\n\n**2. Train each muscle about twice a week**\n\nFor most beginners, full-body workouts 3 days a week or an upper/lower split 4 days a week work well.\n\n**3. Get enough hard sets**\n\nA good target is about 10 to 20 challenging sets per muscle group per week. Beginners often grow well at the lower end. A set is \"hard\" when you finish with only 1 to 3 reps left in the tank.\n\n**4. Focus on the big movements**\n\nSquats or leg press, deadlift variations, presses, rows, and pull-downs give you the most return. Add isolation work like curls, lateral raises, and calf raises to fill in the gaps.\n\n**5. Eat for it**\n\n- Get enough protein (about 0.7 to 1 gram per pound of body weight).\n- A small calorie surplus of 200 to 300 a day helps, though beginners can often build muscle while eating near maintenance.\n\n**6. Recover**\n\nMuscle grows while you rest. Sleep 7 to 9 hours and take rest days.\n\n**Be patient.** Beginners can often gain noticeable muscle in the first 3 to 6 months. Progress slows over time, and that's normal.\n\n**The takeaway:** Lift consistently, add a little more over time, eat enough protein, and sleep well.\n\n*Educational content only, not medical advice. Talk to your doctor before starting a new exercise program.*"
  },
  {
    "id": "starter-4",
    "title": "How Many Calories Should You Eat to Lose Weight?",
    "category": "Fat Loss",
    "excerpt": "Learn how to estimate your calorie needs and set a deficit you can stick with.",
    "date": "2026-09-19",
    "body": "To lose fat, you need to eat fewer calories than your body uses. The trick is finding a number that works without making you miserable.\n\n**Step 1: Estimate your maintenance calories**\n\nMaintenance is the amount you eat to stay the same weight. A rough starting estimate:\n\n**Body weight in pounds x 14 to 16**\n\nUse the lower end if you're less active and the higher end if you're on your feet a lot or train often. Example: a 200 lb person who trains 3 to 4 days a week might start around 2,800 to 3,000.\n\n**Step 2: Create a modest deficit**\n\nSubtract about 300 to 500 calories from maintenance. For most people, this leads to about 0.5 to 1 pound of loss per week. Faster isn't better. Aggressive cuts make it harder to keep muscle, energy, and motivation.\n\n**Step 3: Don't go too low**\n\nVery low intakes can backfire. As a general guide, avoid going below about 1,200 calories (women) or 1,500 calories (men) unless you're working with a medical professional.\n\n**Step 4: Track and adjust**\n\n- Weigh yourself several mornings a week and look at the weekly average, not single days. Daily weight changes from water, salt, and digestion.\n- If your average hasn't moved after 2 to 3 weeks, lower your calories a little or add some steps.\n- If you're losing faster than 1% of your body weight per week, eat a bit more.\n\n**Make the calories work harder**\n\n- Prioritize protein and fiber for fullness.\n- Lift weights to protect your muscle.\n- Plan one flexible meal a week so the plan fits real life.\n\n**The takeaway:** Estimate, subtract a little, track your trend, and adjust. Every calculator is an estimate, so your real results are the best guide.\n\n*Educational content only, not medical advice. Talk to your doctor or a registered dietitian before starting a weight-loss diet, especially if you have a medical condition.*"
  },
  {
    "id": "starter-5",
    "title": "How to Start Working Out: A Simple Beginner's Plan",
    "category": "Training",
    "excerpt": "New to the gym? Here's how to start, what to do, and how to keep going past week two.",
    "date": "2026-09-19",
    "body": "The hardest part of working out is getting started. Here's a simple plan you can follow without feeling lost.\n\n**Start small**\n\nBegin with 3 days a week, with a rest day between sessions. Thirty to 45 minutes is enough. Doing a little consistently beats going all out for one week and quitting.\n\n**Build your workouts around 5 movements**\n\n1. **Squat** (goblet squat or leg press)\n2. **Hinge** (Romanian deadlift or hip thrust)\n3. **Push** (push-up or dumbbell press)\n4. **Pull** (row or lat pull-down)\n5. **Carry or core** (farmer's carry or plank)\n\nDo 2 to 3 sets of 8 to 12 reps of each. Pick a weight that feels challenging but lets you keep good form.\n\n**Warm up first**\n\nSpend 5 to 10 minutes on light cardio and easy versions of your first exercises.\n\n**Learn the form before adding weight**\n\nUse lighter weights until the movement feels smooth. If you're unsure, ask a trainer to check your form. A few sessions early on can save you from bad habits.\n\n**Add walking**\n\nTry a 20 to 30 minute walk on your off days. It helps recovery and builds the habit.\n\n**Make it stick**\n\n- Schedule your workouts like appointments.\n- Log every session so you can see your progress.\n- Expect some soreness in the first couple of weeks. It fades.\n- Focus on showing up, not on perfect workouts.\n\n**Progress it**\n\nWhen you can do all your sets and reps with good form, add a small amount of weight next time.\n\n**The takeaway:** Start with 3 full-body days a week, learn good form, log your workouts, and build from there.\n\n*Educational content only, not medical advice. If you have a health condition or haven't exercised in a long time, check with your doctor before starting.*"
  }
];
